target 'SampleAlamofireMapper' do
    use_frameworks!
    
    pod 'Alamofire',                '~> 4.4'
    pod 'ObjectMapper',             '~> 2.2'
    pod 'PromiseKit',               '~> 4.0'
    pod 'AlamofireObjectMapper',    '~> 4.0'
    
end
